#!/usr/bin/env python3
"""
Demo: Generate a playable ZZT world from scratch using the zzt Python library.

This script creates "DEMO.ZZT" with:
  - A title screen with a welcome scroll
  - A dungeon room with walls, a key, a locked door, and two enemies
  - A treasure room that opens when the player gets the key

Run: python3 examples/generate_demo_world.py
Then open DEMO.ZZT in ZZT or the Zeta emulator.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from zzt.world import (
    World, WorldInfo, Board, BoardInfo, Tile, Stat,
    load_world, save_world, ELEMENT_IDS, BOARD_WIDTH, BOARD_HEIGHT,
)

OUT_PATH = os.path.join(os.path.dirname(__file__), "DEMO.ZZT")

# ─── Color constants (bg<<4 | fg) ────────────────────────────────────────────
WHITE      = 0x0F
YELLOW     = 0x0E
GREEN      = 0x0A
CYAN       = 0x0B
RED        = 0x0C
MAGENTA    = 0x0D
BLUE_FG    = 0x09
BROWN      = 0x06
DARK_GRAY  = 0x08
WHITE_BG   = 0x7F  # white bg, white fg
BLU_ON_BLK = 0x19  # blue on black


def make_stat(x, y, cycle=3, p1=2, p2=0, p3=0, oop_code=b"") -> Stat:
    s = Stat()
    s.x = x; s.y = y
    s.cycle = cycle
    s.p1 = p1; s.p2 = p2; s.p3 = p3
    s.data = oop_code
    return s


def draw_border(board: Board, color: int = WHITE) -> None:
    for x in range(1, BOARD_WIDTH + 1):
        board.set_tile(x, 1,           21, color)
        board.set_tile(x, BOARD_HEIGHT, 21, color)
    for y in range(2, BOARD_HEIGHT):
        board.set_tile(1,           y, 21, color)
        board.set_tile(BOARD_WIDTH, y, 21, color)


def fill_rect(board: Board, x1, y1, x2, y2, elem, color) -> None:
    for y in range(y1, y2 + 1):
        for x in range(x1, x2 + 1):
            board.set_tile(x, y, elem, color)


# ─── Title Screen (board 0) ───────────────────────────────────────────────────

def make_title_board() -> Board:
    b = Board()
    b.name = "CLAUDE DUNGEON"

    draw_border(b, YELLOW)

    # Center text label art (using Text elements = 47..53, but for simplicity use Objects)
    # Place a Scroll object that shows the intro
    intro_scroll = (
        "@intro\n"
        "$Welcome to Claude Dungeon!\n"
        "\n"
        "A dungeon generated by Claude Code\n"
        "using the ZZT MCP integration.\n"
        "\n"
        "Find the key, unlock the door,\n"
        "reach the treasure room to win!\n"
        "\n"
        "Press any key to begin.\n"
        "#end\n"
    )

    scroll_stat = make_stat(30, 12, cycle=1, p1=232, oop_code=intro_scroll.encode())
    b.set_tile(30, 12, 10, YELLOW)   # element 10 = Scroll
    b.stats.append(scroll_stat)

    # Player stat (always index 0 effectively — added first before scroll)
    player = make_stat(30, 12)
    b.stats.insert(0, player)

    b.info.neighbor_south = 1  # links to board 1

    return b


# ─── Dungeon Room (board 1) ───────────────────────────────────────────────────

def make_dungeon_board() -> Board:
    b = Board()
    b.name = "The Dungeon"

    # Solid outer walls
    draw_border(b, WHITE)

    # Fill floor with a subtle forest background
    fill_rect(b, 2, 2, BOARD_WIDTH - 1, BOARD_HEIGHT - 1, 0, 0x00)  # empty floor

    # Interior walls — create a simple maze shape
    # North room divider
    for x in range(2, 40):
        b.set_tile(x, 10, 21, WHITE)
    # Gap at x=20 (passage through wall)
    b.set_tile(20, 10, 0, 0)

    # East wall section
    for y in range(10, BOARD_HEIGHT):
        b.set_tile(40, y, 21, WHITE)
    # Gap at y=18 (door location)
    b.set_tile(40, 18, 9, YELLOW)   # element 9 = Door (yellow = needs yellow key)

    # ── Key (top section) ──
    b.set_tile(10, 5, 8, YELLOW)    # element 8 = Key (yellow)

    # ── Bear enemy in top section ──
    bear_oop = b"@guard1\n/i\n?n\n?s\n?e\n?w\n#end\n"
    bear_stat = make_stat(15, 5, cycle=3, p1=153, oop_code=bear_oop)
    b.set_tile(15, 5, 34, BROWN)    # element 34 = Bear
    b.stats.append(bear_stat)

    # ── Ruffian enemy in bottom section ──
    ruff_oop = b"@ruffian\n/i\n/i\n?n\n?s\n?e\n?w\n#end\n"
    ruff_stat = make_stat(25, 18, cycle=4, p1=5, oop_code=ruff_oop)
    b.set_tile(25, 18, 35, RED)     # element 35 = Ruffian
    b.stats.append(ruff_stat)

    # ── Ammo pickup object ──
    ammo_oop = (
        "@ammo_cache\n"
        "You find a stash of ammo!\n"
        "#give ammo 5\n"
        "#become empty\n"
    ).encode()
    b.set_tile(35, 5, 5, CYAN)      # element 5 = Ammo
    ammo_stat = make_stat(35, 5, cycle=1, oop_code=ammo_oop)
    b.stats.append(ammo_stat)

    # ── Torch ──
    b.set_tile(8, 8, 6, BROWN)      # element 6 = Torch

    # ── Hint object (exclamation mark style) ──
    hint_oop = (
        "@hint\n"
        "$Dungeon Hint\n"
        "\n"
        "Find the YELLOW KEY\n"
        "to open the YELLOW DOOR\n"
        "in the east wall!\n"
        "#end\n"
    ).encode()
    hint_stat = make_stat(3, 3, cycle=1, p1=ord('!'), oop_code=hint_oop)
    b.set_tile(3, 3, 36, YELLOW)    # element 36 = Object
    b.stats.append(hint_stat)

    # Player starting position
    player = make_stat(5, 15)
    b.stats.insert(0, player)

    b.info.player_enter_x = 5
    b.info.player_enter_y = 15
    b.info.neighbor_north = 0   # back to title
    b.info.neighbor_east  = 2   # treasure room

    return b


# ─── Treasure Room (board 2) ─────────────────────────────────────────────────

def make_treasure_board() -> Board:
    b = Board()
    b.name = "The Treasure Chamber"

    draw_border(b, YELLOW)

    # Gold floor feel
    fill_rect(b, 2, 2, BOARD_WIDTH - 1, BOARD_HEIGHT - 1, 0, 0x00)

    # Scatter gems
    gem_positions = [(15,6),(20,6),(25,6),(30,6),(35,6),(40,6),(45,6),
                     (15,12),(20,12),(25,12),(35,12),(40,12),(45,12),
                     (15,18),(25,18),(30,18),(35,18),(45,18)]
    for gx, gy in gem_positions:
        b.set_tile(gx, gy, 7, GREEN)    # element 7 = Gem

    # Energizer
    b.set_tile(30, 12, 14, MAGENTA)     # element 14 = Energizer

    # Win object
    win_oop = (
        "@victory\n"
        "$You Win!\n"
        "\n"
        "Congratulations!\n"
        "You escaped the dungeon!\n"
        "\n"
        "This world was generated by\n"
        "Claude Code via the ZZT MCP\n"
        "integration.\n"
        "\n"
        "Press ESCAPE to quit.\n"
        "#end\n"
    ).encode()
    win_stat = make_stat(30, 8, cycle=1, p1=ord('W'), oop_code=win_oop)
    b.set_tile(30, 8, 36, YELLOW)
    b.stats.append(win_stat)

    # Player entry
    player = make_stat(3, 12)
    b.stats.insert(0, player)
    b.info.player_enter_x = 3
    b.info.player_enter_y = 12
    b.info.neighbor_west  = 1   # back to dungeon

    return b


# ─── Assemble and save ────────────────────────────────────────────────────────

def main():
    world_info = WorldInfo()
    world_info.name          = "CLAUDE DUNGEON"
    world_info.health        = 100
    world_info.ammo          = 5
    world_info.current_board = 0   # start on title

    world = World(info=world_info)
    world.boards.append(make_title_board())
    world.boards.append(make_dungeon_board())
    world.boards.append(make_treasure_board())

    save_world(world, OUT_PATH)
    print(f"Saved: {OUT_PATH}")
    print(f"  Boards : {len(world.boards)}")
    for i, brd in enumerate(world.boards):
        print(f"  [{i}] {brd.name!r:30s}  stats={len(brd.stats)}")
    print()
    print("Open DEMO.ZZT in ZZT or the Zeta emulator:")
    print("  https://github.com/asiekierka/zeta")


if __name__ == "__main__":
    main()
